/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ChocolatesRouteImport } from './routes/chocolates'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CustomiseRouteImport } from './routes/customise'
import { Route as DryFruitsRouteImport } from './routes/dry-fruits'
import { Route as GiftBoxRouteImport } from './routes/gift-box'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as StoryRouteImport } from './routes/story'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as OrderOrderNumberRouteImport } from './routes/order.$orderNumber'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ChocolatesRoute = ChocolatesRouteImport.update({
  id: '/chocolates',
  path: '/chocolates',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomiseRoute = CustomiseRouteImport.update({
  id: '/customise',
  path: '/customise',
  getParentRoute: () => rootRouteImport,
} as any)
const DryFruitsRoute = DryFruitsRouteImport.update({
  id: '/dry-fruits',
  path: '/dry-fruits',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftBoxRoute = GiftBoxRouteImport.update({
  id: '/gift-box',
  path: '/gift-box',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderOrderNumberRoute = OrderOrderNumberRouteImport.update({
  id: '/order/$orderNumber',
  path: '/order/$orderNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/chocolates': typeof ChocolatesRoute
  '/contact': typeof ContactRoute
  '/customise': typeof CustomiseRoute
  '/dry-fruits': typeof DryFruitsRoute
  '/gift-box': typeof GiftBoxRoute
  '/shop': typeof ShopRoute
  '/story': typeof StoryRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin/login': typeof AdminLoginRoute
  '/order/$orderNumber': typeof OrderOrderNumberRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/chocolates': typeof ChocolatesRoute
  '/contact': typeof ContactRoute
  '/customise': typeof CustomiseRoute
  '/dry-fruits': typeof DryFruitsRoute
  '/gift-box': typeof GiftBoxRoute
  '/shop': typeof ShopRoute
  '/story': typeof StoryRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin/login': typeof AdminLoginRoute
  '/order/$orderNumber': typeof OrderOrderNumberRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/chocolates': typeof ChocolatesRoute
  '/contact': typeof ContactRoute
  '/customise': typeof CustomiseRoute
  '/dry-fruits': typeof DryFruitsRoute
  '/gift-box': typeof GiftBoxRoute
  '/shop': typeof ShopRoute
  '/story': typeof StoryRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/admin/login': typeof AdminLoginRoute
  '/order/$orderNumber': typeof OrderOrderNumberRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/checkout'
    | '/chocolates'
    | '/contact'
    | '/customise'
    | '/dry-fruits'
    | '/gift-box'
    | '/shop'
    | '/story'
    | '/admin'
    | '/admin/login'
    | '/order/$orderNumber'
    | '/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/chocolates'
    | '/contact'
    | '/customise'
    | '/dry-fruits'
    | '/gift-box'
    | '/shop'
    | '/story'
    | '/admin'
    | '/admin/login'
    | '/order/$orderNumber'
    | '/product/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cart'
    | '/checkout'
    | '/chocolates'
    | '/contact'
    | '/customise'
    | '/dry-fruits'
    | '/gift-box'
    | '/shop'
    | '/story'
    | '/_authenticated/admin'
    | '/admin/login'
    | '/order/$orderNumber'
    | '/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ChocolatesRoute: typeof ChocolatesRoute
  ContactRoute: typeof ContactRoute
  CustomiseRoute: typeof CustomiseRoute
  DryFruitsRoute: typeof DryFruitsRoute
  GiftBoxRoute: typeof GiftBoxRoute
  ShopRoute: typeof ShopRoute
  StoryRoute: typeof StoryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  OrderOrderNumberRoute: typeof OrderOrderNumberRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chocolates': {
      id: '/chocolates'
      path: '/chocolates'
      fullPath: '/chocolates'
      preLoaderRoute: typeof ChocolatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customise': {
      id: '/customise'
      path: '/customise'
      fullPath: '/customise'
      preLoaderRoute: typeof CustomiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dry-fruits': {
      id: '/dry-fruits'
      path: '/dry-fruits'
      fullPath: '/dry-fruits'
      preLoaderRoute: typeof DryFruitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-box': {
      id: '/gift-box'
      path: '/gift-box'
      fullPath: '/gift-box'
      preLoaderRoute: typeof GiftBoxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$orderNumber': {
      id: '/order/$orderNumber'
      path: '/order/$orderNumber'
      fullPath: '/order/$orderNumber'
      preLoaderRoute: typeof OrderOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ChocolatesRoute: ChocolatesRoute,
  ContactRoute: ContactRoute,
  CustomiseRoute: CustomiseRoute,
  DryFruitsRoute: DryFruitsRoute,
  GiftBoxRoute: GiftBoxRoute,
  ShopRoute: ShopRoute,
  StoryRoute: StoryRoute,
  AdminLoginRoute: AdminLoginRoute,
  OrderOrderNumberRoute: OrderOrderNumberRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
